{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lobstr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lobstr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lobstr/lobstr_{{ version }}.tar.gz
  sha256: 5cdadf420cb8877e442aff50beb191d13b69c51911d402a6c50b07666237de4b

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rlang >=1.0.0            # [build_platform != target_platform]
    - r-crayon                   # [build_platform != target_platform]
    - r-cpp11 >=0.4.2            # [build_platform != target_platform]
    - r-prettyunits              # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cpp11 >=0.4.2
    - r-crayon
    - r-prettyunits
    - r-rlang >=1.0.0
  run:
    - r-base
    - r-cpp11 >=0.4.2
    - r-crayon
    - r-prettyunits
    - r-rlang >=1.0.0

test:
  commands:
    - $R -e "library('lobstr')"           # [not win]
    - "\"%R%\" -e \"library('lobstr')\""  # [win]

about:
  home: https://github.com/r-lib/lobstr
  license: MIT
  summary: A set of tools for inspecting and understanding R data structures inspired by str(). Includes ast() for visualizing abstract  syntax trees, ref() for showing shared references, cst() for showing  call stack trees, and obj_size() for computing object sizes.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
