travis:
  secure:
    BINSTAR_TOKEN: PLyhkqJa6XA9XLsMCiWfyeZjHMfCDg50tUshiAi44EuhSX/ImYHbN3PeLovdsG44Sy3P1rEIS1ZelrLyRRbt6nDfIAvmVCNdNW0GqZr3ZzA07KkzdNeprr/Z1PCeOV7rZvow+3gWWcsl54/JCcoblFLRH3jigqdCJOEEQowxt5Mcr9ip6IaVOU51jC/TxsiarTn1Ps//7rT+dGGOo67UwxYJ2k1b7SfAEsOX82Mr15CMbr+u0kp8gRZG7n7/cfr/AwdS6mGNGzMi1TLhH8bocDrm1tBI7Fjjm030UnUBMLH+YIrRljC0gHyPx2htN1SSnMdEclPcyhY4GhSjmZYiFChB00z5+591jbu7z3L6vVBSXKK3dCxyBgw1RcH/qfrkuErFcsJpRMK0eiGjxbfSjUOd9/JzkIH9QiFO11aw41rweXWnBBd0cQQFk9Dpy/N1jSw0OAiqtSe0q1MTwc06QpalEZPkFFNrrKtE/dFYtXfgRPp0hJURX0Fj72pqyTJvD4NCySWzQZCozqibAsdv5zBg0phPpqWP9IsK3bdoFCyYenADMYwoLsLOdYrcpioHmZ3Xu7rHLDNdrjmRMh7M+e9QFuoY03vbTZnjSidBP1DQ8uY+EV5JWKA995YndPeklwyXUoeWBw048Hu6Ms0XV54InNtT9lSl29N7JufqWKw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
